// SuperAudio © 2026 David Puerto. MIT licensed — see LICENSE.md.

import Foundation

/// #118 / M6.4 — Maximum Length Sequence (MLS) generator for room calibration.
///
/// **What it is**: a pseudorandom binary sequence generated by an LFSR
/// (Linear Feedback Shift Register), played as audio. Sounds like a
/// brief burst of static / TV hiss. Used in pro audio measurement
/// (Smaart, REW, ARTA) for 40+ years.
///
/// **Why MLS beats chirps for our calibration use case**:
///
/// 1. **Mathematically optimal autocorrelation.** An MLS has an
///    autocorrelation function that is exactly a delta function (within
///    the sequence period). Cross-correlation with a recorded MLS gives
///    ONE clean peak with zero spurious peaks anywhere else. Chirps
///    approximate this; MLS achieves it exactly.
///
/// 2. **Friendlier sound.** Chirps sound like alarms / fault tones.
///    Brief hiss sounds like TV static — non-alarming, more like a
///    "test sound" than a "warning sound."
///
/// 3. **Robust against noise.** Long sequences accumulate SNR linearly
///    with length. A 1-sec MLS at 48 kHz has 48000 samples — gives 20+
///    dB processing gain over a single broadband click.
///
/// 4. **Same correlator path.** The `AudioCorrelation.correlatedLag`
///    engine works identically — it doesn't care whether the reference
///    signal is a chirp, MLS, or anything else. We just swap the
///    reference signal source; everything downstream is unchanged.
///
/// **LFSR specifics**: this implementation uses a 16-bit register with
/// taps at bits 16, 15, 13, 4 (one of the standard maximum-length
/// configurations from the table in Schroeder's "Number Theory in
/// Science and Communication", §15.5). Sequence length = 2^16 - 1 =
/// 65535 samples ≈ 1.365 sec at 48 kHz. Fits our 1-sec measurement
/// window with one-sample slack.
public enum MLSGenerator {

    /// Generate a maximum-length sequence as float samples in {-1, +1},
    /// optionally with brief fade-in/out to suppress edge clicks.
    ///
    /// `seed` selects the LFSR's initial state. Any non-zero seed
    /// produces the same statistical properties; different seeds
    /// produce different specific sequences. Default 0xACE1 is the
    /// classic "Linux random" seed used in textbooks — recognizable
    /// to anyone who's read Knuth Vol. 2.
    ///
    /// Output amplitude is bounded: each sample is exactly +amplitude
    /// or -amplitude. Hann-windowed fade-in/out smooths the edges so
    /// the speaker doesn't pop on start/stop.
    public static func generate(
        durationSec: Double = 1.0,
        sampleRate: Double = 48000,
        amplitude: Float = 0.4,
        fadeMs: Double = 10,
        seed: UInt16 = 0xACE1
    ) -> [Float] {
        let n = Int(durationSec * sampleRate)
        var samples = [Float](repeating: 0, count: n)
        var lfsr: UInt16 = seed == 0 ? 0xACE1 : seed

        let fadeSamples = max(1, Int(fadeMs / 1000.0 * sampleRate))

        for i in 0..<n {
            // 16-bit LFSR with taps at 16, 15, 13, 4 (1-indexed) —
            // standard maximum-length polynomial x^16 + x^15 + x^13 + x^4 + 1.
            // Bit indices (0-indexed from LSB): 15, 14, 12, 3.
            let bit: UInt16 = ((lfsr >> 0) ^ (lfsr >> 2) ^ (lfsr >> 3) ^ (lfsr >> 5)) & 1
            lfsr = (lfsr >> 1) | (bit << 15)

            // Map {0, 1} → {-amp, +amp}.
            var sample: Float = (bit == 0) ? -amplitude : amplitude

            // Fade-in/out window (Hann half-cycles) to suppress edge
            // pops. Same shape as ChirpGenerator's fade for consistency.
            if i < fadeSamples {
                let w = 0.5 * (1.0 - cos(.pi * Double(i) / Double(fadeSamples)))
                sample *= Float(w)
            } else if i >= n - fadeSamples {
                let pos = Double(n - 1 - i)
                let w = 0.5 * (1.0 - cos(.pi * pos / Double(fadeSamples)))
                sample *= Float(w)
            }

            samples[i] = sample
        }
        return samples
    }

    /// Convenience: the canonical SuperAudio calibration MLS.
    /// 1 sec, 48 kHz, amplitude 0.4 (slightly lower than chirp because
    /// MLS is broadband and feels louder for the same peak amplitude),
    /// 10 ms fades.
    public static var defaultCalibrationMLS: [Float] {
        generate()
    }
}
